### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by willforde** [callmonitoring/call_monitoring#3]
### This is a list of all tasks left to do in order to finish the project. (I Hope)

- [ ] Create model that will be used to populate the callbacks model on a schedule
- [ ] Add code to auto update the callback list with a set of numbers on a schedule
- [ ] Find out what are the best permissions to give the users
- [ ] Add function to remove stale incoming records on a schedule. Stale records can happen after a crash.
- [ ] Cleanup missed model and do filtering based on the call field, hint use call__
- [ ] Find a better way to do the update method of CreateContactMixin
- [ ] Change front page login label to show logout if user is already logged in
- [ ] In the front page add a link to the dashboard, redirect to login page if user is not logged in
- [ ] Remove the unused links in the front page, About, Services, Contact?
- [ ] Change dashboard to only show the most recent call logs with no paging support.
- [ ] Switch to using a normal table to show call logs on the call logs, missed calls and callback, pages.
- [ ] Setup filtering on the normal tables
- [ ] Maybe have the dashboard datatables flash with a colour when a new call log appears.
- [ ] Get the contacts importer working
- [ ] Look into using user profiles.

**Comment by willforde** [comment]
Options for the tables.
django-tables2 = https://django-tables2.readthedocs.io/en/latest/
django-datatables-view = https://bitbucket.org/pigletto/django-datatables-view

**Comment by willforde** [comment]
## Version 2.0

- [ ] Add support for webhooks.

### References
webhooks: https://djangopackages.org/grids/g/webhooks/
